### ISSUE TITLE
One full run of the Companies House ETL

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#569]
Just to account for some time, since this gave us trouble in the previous sprint.

Blocked by #551, #552, #527 and #563: not useful doing until Sorting Office is more robust.

**Comment by pezholio** [comment]
This is ready to go I reckon now

**Comment by giacecco** [comment]
Was the new CH ETL adapted to use https://github.com/theodi/shared/issues/551 ? If so, and https://github.com/theodi/shared/issues/551 is merged, what is stopping us from proceeding?

**Comment by pezholio** [comment]
I've kicked off one of the bots now. Will see how it goes and kick the other ones off if that one runs cleanly

**Comment by giacecco** [comment]
How did it go?

**Comment by pezholio** [comment]
Failed after 4900 records. I'll have to check out what happened.

**Comment by pezholio** [comment]
So, here's the error:

```
/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/protocol.rb:143:in `select': Interrupt
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/protocol.rb:143:in `rescue in rbuf_fill'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:1294:in `request'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:1287:in `block in request'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:746:in `start'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/httparty-0.13.1/lib/httparty/request.rb:93:in `perform'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/httparty-0.13.1/lib/httparty.rb:473:in `post'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/httparty-0.13.1/lib/httparty.rb:563:in `post'
	from /repo/companies_house.rb:124:in `request_with_retries'
	from /repo/companies_house.rb:63:in `parse_address'
	from /repo/companies_house.rb:51:in `block in parse_csv'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/csv.rb:1792:in `each'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/csv.rb:1208:in `block in foreach'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/csv.rb:1354:in `open'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/csv.rb:1207:in `foreach'
	from /repo/companies_house.rb:49:in `parse_csv'
	from /repo/companies_house.rb:43:in `block (2 levels) in read_zip'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/entry_set.rb:42:in `call'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/entry_set.rb:42:in `block in each'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/entry_set.rb:41:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/entry_set.rb:41:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/central_directory.rb:182:in `each'
	from /repo/companies_house.rb:38:in `block in read_zip'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/file.rb:99:in `open'
	from /repo/companies_house.rb:37:in `read_zip'
	from /repo/companies_house.rb:26:in `process'
	from /repo/companies_house.rb:15:in `run'
	from scraper.rb:9:in `<main>'
```

No idea what's happened there

**Comment by pezholio** [comment]
This is still crapping out. Same issue. I'm going to schedule another run and keep watching it. It's very strange.

**Comment by pezholio** [comment]
Actually, this seemed like a different error now, but still http related:

```
/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:763:in `initialize': Interrupt
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:763:in `open'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:763:in `connect'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:745:in `start'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/httparty-0.13.1/lib/httparty/request.rb:93:in `perform'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/httparty-0.13.1/lib/httparty.rb:473:in `post'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/httparty-0.13.1/lib/httparty.rb:563:in `post'
	from /repo/companies_house.rb:124:in `request_with_retries'
	from /repo/companies_house.rb:63:in `parse_address'
	from /repo/companies_house.rb:51:in `block in parse_csv'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/csv.rb:1792:in `each'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/csv.rb:1208:in `block in foreach'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/csv.rb:1354:in `open'
	from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/csv.rb:1207:in `foreach'
	from /repo/companies_house.rb:49:in `parse_csv'
	from /repo/companies_house.rb:43:in `block (2 levels) in read_zip'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/entry_set.rb:42:in `call'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/entry_set.rb:42:in `block in each'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/entry_set.rb:41:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/entry_set.rb:41:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/central_directory.rb:182:in `each'
	from /repo/companies_house.rb:38:in `block in read_zip'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rubyzip-1.1.4/lib/zip/file.rb:99:in `open'
	from /repo/companies_house.rb:37:in `read_zip'
	from /repo/companies_house.rb:26:in `process'
	from /repo/companies_house.rb:15:in `run'
	from scraper.rb:9:in `<main>'
```

I should be catching any errors and retrying, see https://github.com/OpenAddressesUK/companies_house/blob/master/companies_house.rb#L123. Am I missing anything?

**Comment by Floppy** [comment]
@pikesley just realised I'm not an admin on turbot, so I can't see what state this is in. Can you check it out and see how it is?

**Comment by pikesley** [comment]
![screenshot 2015-04-14 15 18 43](https://cloud.githubusercontent.com/assets/885973/7138678/c201a97e-e2b9-11e4-987b-475f8cc1d20e.png)

AMAZE

**Comment by pikesley** [comment]
![screenshot 2015-04-15 09 42 05](https://cloud.githubusercontent.com/assets/885973/7155082/babb6a84-e353-11e4-990c-e377996e4db4.png)

Day 2, and it's still pumping (I think _4 may have actually completed)

**Comment by Floppy** [comment]
impressive...

**Comment by pezholio** [comment]
(╯°□°）╯︵ ┻━┻

```
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/rest-3.0.6/lib/rest/wrappers/rest_client_wrapper.rb:75:in `rescue in post': HTTP 500 Error: internal error (Rest::Wrappers::RestClientExceptionWrapper)
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rest-3.0.6/lib/rest/wrappers/rest_client_wrapper.rb:62:in `post'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rest-3.0.6/lib/rest/client.rb:204:in `block in post'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rest-3.0.6/lib/rest/client.rb:151:in `perform_op'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rest-3.0.6/lib/rest/client.rb:203:in `post'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/iron_core-1.0.7/lib/iron_core/client.rb:241:in `post'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/iron_mq-5.0.1/lib/iron_mq/queues.rb:243:in `call_api_and_parse_response'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/iron_mq-5.0.1/lib/iron_mq/queues.rb:166:in `post_messages'
	from /utils/wrapper.rb:31:in `handle_valid_record'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/turbot-runner-0.1.27/lib/turbot_runner/processor.rb:24:in `process'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/turbot-runner-0.1.27/lib/turbot_runner/script_runner.rb:55:in `block in run'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/turbot-runner-0.1.27/lib/turbot_runner/script_runner.rb:19:in `chdir'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/turbot-runner-0.1.27/lib/turbot_runner/script_runner.rb:19:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/turbot-runner-0.1.27/lib/turbot_runner/runner.rb:92:in `run_script'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/turbot-runner-0.1.27/lib/turbot_runner/runner.rb:27:in `run'
	from /utils/wrapper.rb:82:in `<main>'

```

**Comment by Floppy** [comment]
Could it have filled the IronMQ queue?

**Comment by Floppy** [comment]
There is a maximum queue size on our account...

**Comment by pezholio** [comment]
Limit is 10m per month, so I don't think it's that

**Comment by Floppy** [comment]
we've run a few though... which failed, but... worth checking.

**Comment by pezholio** [comment]
Yeah, we don't seem to be anywhere near the limit. Also tried manually pushing some up and it worked without complaint.

Dunno if we need to put some logic [here](https://github.com/OpenAddressesUK/chas/blob/master/utils/wrapper.rb#L31) to guard against any short outages

**Comment by Floppy** [comment]
That's good. Best to be defensive, yes.

**Comment by pezholio** [comment]
Right. This is done now, and chugging away happily

**Comment by pikesley** [comment]
Bot _3 blew up

    /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/csv.rb:1894:in `block (2 levels) in shift': Missing or stray quote in line 745250 (CSV::MalformedCSVError)

and now I hate everything

**Comment by pezholio** [comment]
BOOM! It WORKED! http://turbot.openaddressesuk.org/admin/bots/companies_house_3
